name: messenger_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  cloud_functions: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  firebase_storage: ^12.0.0
  messenger:
    path: ../messenger/messenger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
