// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxMeHAdAed5CfrgeBWDm6KFhM87Pu__jc',
    appId: '1:391873827077:web:7a5c96f1b87af1ce8b676c',
    messagingSenderId: '391873827077',
    projectId: 'messenger-4ebe1',
    authDomain: 'messenger-4ebe1.firebaseapp.com',
    storageBucket: 'messenger-4ebe1.appspot.com',
    measurementId: 'G-YCQHLWL9R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJExKWJpHGPDofJnySkMQbM7nE8ccOSM',
    appId: '1:391873827077:android:2dad97b2230fb6398b676c',
    messagingSenderId: '391873827077',
    projectId: 'messenger-4ebe1',
    storageBucket: 'messenger-4ebe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYLKWumBx-eBR4EGfGUSfwk2PjIMM-c8',
    appId: '1:391873827077:ios:600fb123272324ad8b676c',
    messagingSenderId: '391873827077',
    projectId: 'messenger-4ebe1',
    storageBucket: 'messenger-4ebe1.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYLKWumBx-eBR4EGfGUSfwk2PjIMM-c8',
    appId: '1:391873827077:ios:600fb123272324ad8b676c',
    messagingSenderId: '391873827077',
    projectId: 'messenger-4ebe1',
    storageBucket: 'messenger-4ebe1.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxMeHAdAed5CfrgeBWDm6KFhM87Pu__jc',
    appId: '1:391873827077:web:c527cf7d20b5a4d58b676c',
    messagingSenderId: '391873827077',
    projectId: 'messenger-4ebe1',
    authDomain: 'messenger-4ebe1.firebaseapp.com',
    storageBucket: 'messenger-4ebe1.appspot.com',
    measurementId: 'G-8ZR8DZCGB7',
  );

}